In [3]:
import streamlit as st
import tkinter as tk
import matplotlib.font_manager as fm
import urllib.request
import gspread
import os
import pandas as pd
from datetime import datetime, timedelta

# Download Sarabun font if it doesn't exist
if not os.path.exists("Sarabun-Regular.ttf"):
    urllib.request.urlretrieve(
        "https://github.com/google/fonts/raw/main/ofl/sarabun/Sarabun-Regular.ttf",
        "Sarabun-Regular.ttf",
    )

# Add Sarabun font to the font manager
if "Sarabun" not in [x.name for x in fm.fontManager.ttflist]:
    fm.fontManager.addfont("Sarabun-Regular.ttf")

# Add your Google Service Account JSON key here
jsonkey = {
    "type": "service_account",
    "project_id": "genuine-ember-403902",
    "private_key_id": "9caa1a0008f5a0965818366654cbca20e79800dc",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDwlqbNPUlddfYV\nlxTbGZf6Vn9HSWoGJVfKeZSz9jH9ajPwPv9cYQWP2ti+bMsprSoka006SxPMyrTj\nU078JfAotKBBebhhCkVh7pn1f42PQS+5UUy90kGaEEC5/SMpbDV2muoNF3VWqzhu\nh1qCcq/8M2SE1znz1wOQFaynx00ZyjVF4WWIXUxpOHIbB2CprMMVZDZZfDT0R1Go\n27YENnxjibWOjqq+YfPNzk43eoQ4RBI2W8sB/EyqF/tJXiQ1sayTpB1/zRrjBLCw\ndiK7u5+zhJfTT0kQsklsWj52dMo713u2hS+W0poUYx5CbFjx9V40NRup/3GvEUNb\nJ2Hkcg5hAgMBAAECggEAC7fKuARcJmkwayzIn0NH27GK0XYJ6/K1q+7wBzPei3E4\nxmLLHTy8gJ0wIVY7LvR4MP3o7QXrGPZmiQvttOpEIDdr9sRu7osJhhOQ/BwSUP/j\nyyriifxLpa1U+boSlFno4LX64FhcJrSAMyH0jpX3bFk0dCPndrDqQ4JKvoE+iBrx\nAGL3b8w5W1GROTWrrRRVMemjSLWOsZJ9zKe4Z5tdTUkuwiJnonFk+vwDukpYnxdv\nxHyWq39yrfXCqx3dmGPLrJhbnNHsWLc0K5xZImKTbbIiJcPkPwvgwj0bCwC56dWg\nhtaWZbzBrhED5CN6sj94hm7/nEK+cubOxPS8AvFqAQKBgQD5TvFy3qU/g5Hr9ZBe\n+g+z48rDeqz8CODYtAMxxwdkStedc/JZ/hpeK3luIsBjlYIH7oGb4Gpu3ZmEgLL4\ndawuHeLXljmwov3KUhCH906x4baYe929r94ACEKaeGoY3hCItI4aAWTSyrUbvj0U\nUBjAjOcZKWtce9J2zOfXQrpNaQKBgQD3C8q/wSopzlF3zu/gvl6kL8SpN+zItWkW\n3AWqJcivdn3MxS8Z03H6A8aK4jHft+0ef1KNcKNV/JQ6ZxocfdMfeKO+HmKPQGJB\n5HNW294G0gAOG0o+yq8W2vXahR4wMtOXirKnhccCFsbgGRZWx4ro46dZf79+nLA6\nnBUeOfwCOQKBgB0eyncXaIflr1q3YTimzsS9W8a/gosh4lmNlT3wOH3PfCXpECrQ\n0nWjcFib+IrpQLn6cuspKGVwvujKO51n6Uett/xkkLKAJ1LFiSbIjUmbyr8+4KSy\ncSTh0h3G6OWkspu1M0/4T7WLdeIas3m27V04WBoJS4AO+oNj5cSwB6DZAoGBAKE7\nXPORCgeG07yxnfS7yeC2HE+kZDEJ1LBKoJfPWQ7K8od2GattSHG3jRiPT6WG0Iaa\n6jHNVYyE7+i96Vi29dcQUS1/fyunBXmjs3L4xAsHe2m5fddFSMhN1y7qui0Svu2k\nY7zZnmxKmTkgpme0i4A7M7lBmqTzdkCKJW44wbRhAoGBAJZcKnxjBHo3dBwauByN\nYc2iJuvNlc0PN6Jn2urPQcm1qh4eP+CjDtTgJVpB1UBLb/duSxcuVQC8pchdCXRt\n4sP5VFbsVW0Gq1fUQ37jbstso3XmGJfS8Cr8wiyVpwfA+H966bbJ5v8hS59yVniS\nKvgqUpUoCD266W8MnX4Z0eac\n-----END PRIVATE KEY-----\n",
    "client_email": "rpa-643@genuine-ember-403902.iam.gserviceaccount.com",
    "client_id": "101215475468738013271",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/rpa-643%40genuine-ember-403902.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com",
}

gc = gspread.service_account_from_dict(jsonkey)
sheet = gc.open_by_key("1B_FnuPQoHofDFm3QJdDkv-8DkkStixeBmYBGOg6x-eU")
logscan = sheet.worksheet("porterdb")

# Fetch and print data
cache_data = pd.DataFrame(logscan.get_all_records())

In [6]:
cache_data.rename(columns={
    'วัน/เวลา': 'Date/Time',
    'ชื่อ': 'Name',
    'หน้าบ้าน': 'Front House',
    'ในเครื่อง': 'In Machine',
    'รับงาน': 'Receive Work',
    'ไม่อยู่': 'Not Available',
    'พัก': 'Break',
    'เลิกงาน': 'End Work',
    'เรียกครั้งแรก': 'First Call',
    'เรียกครั้งสุดท้าย': 'Last Call',
    'จบที่': 'End At'
}, inplace=True)

cache_data = cache_data[['Date/Time','First Call','Last Call','End At']]
cache_data

                 Date/Time First Call Last Call     End At
0       2024-12-01 5:55:51    5:57:38   5:57:43  ในเครื่อง
1       2024-12-01 5:56:36    5:59:56   5:59:59   หน้าบ้าน
2       2024-12-01 5:57:44    6:00:24   6:00:27   หน้าบ้าน
3       2024-12-01 5:57:54    6:04:36   6:04:37   หน้าบ้าน
4       2024-12-01 5:57:57    6:04:42   6:04:44  ในเครื่อง
...                    ...        ...       ...        ...
29604  2024-12-26 20:44:01    เลิกงาน   เลิกงาน    เลิกงาน
29605  2024-12-26 20:44:04    เลิกงาน   เลิกงาน    เลิกงาน
29606  2024-12-26 20:44:07    เลิกงาน   เลิกงาน    เลิกงาน
29607  2024-12-26 20:44:12    เลิกงาน   เลิกงาน    เลิกงาน
29608  2024-12-26 20:44:18    เลิกงาน   เลิกงาน    เลิกงาน

[29609 rows x 4 columns]

In [7]:
cache_data = cache_data[(cache_data['First Call'].notna()) & (cache_data['First Call'] != '') &
                        (cache_data['Last Call'].notna()) & (cache_data['Last Call'] != '') &
                        (cache_data['End At'].notna()) & (cache_data['End At'] != '')]
cache_data

                 Date/Time First Call Last Call     End At
0       2024-12-01 5:55:51    5:57:38   5:57:43  ในเครื่อง
1       2024-12-01 5:56:36    5:59:56   5:59:59   หน้าบ้าน
2       2024-12-01 5:57:44    6:00:24   6:00:27   หน้าบ้าน
3       2024-12-01 5:57:54    6:04:36   6:04:37   หน้าบ้าน
4       2024-12-01 5:57:57    6:04:42   6:04:44  ในเครื่อง
...                    ...        ...       ...        ...
29604  2024-12-26 20:44:01    เลิกงาน   เลิกงาน    เลิกงาน
29605  2024-12-26 20:44:04    เลิกงาน   เลิกงาน    เลิกงาน
29606  2024-12-26 20:44:07    เลิกงาน   เลิกงาน    เลิกงาน
29607  2024-12-26 20:44:12    เลิกงาน   เลิกงาน    เลิกงาน
29608  2024-12-26 20:44:18    เลิกงาน   เลิกงาน    เลิกงาน

[29527 rows x 4 columns]